[FUTURE CONSIDERATION] Add CC Donation Modal to CC Global Components
creativecommons/cc-global-components pull request #4
Opened 2021-12-03 08:01 UTC by MuluhGodson

## Fixes

Fixes #[issue number] by @[issue author]

## Description
This PR adds the CC Global Donation modal as a Vue Component. 

## Technical details
This component sets a cookie and if the modal is close by the user, the modal doesn't display until the cookie expires.

## Tests
Pull the commit. 
Run `npm run serve` or serve the file `example.html`

## Screenshots
Donation modal with cookie expiry time set to 10 secsonds.
https://user-images.githubusercontent.com/40151808/144566703-aec0d8f5-6565-463f-8c3b-2330604557ac.mp4

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-12-03 08:03 UTC, MuluhGodson commented on src/components/cc-donate.vue
> +      expiryPeriodInDays: 5,
Here is where we enter the number of days the Cookie should be active for.

2021-12-07 07:10 UTC, brylie requested changes

2021-12-07 07:10 UTC, brylie commented on README.md
> +  - - `cc-donate.vue`: The component for the CC Donatiion modal.
```suggestion
  - - `cc-donate.vue`: The component for the CC Donation modal.
```

2021-12-07 07:10 UTC, brylie commented on example.html
> +    <!-- Div element use to mound the CC Donate modal-->
```suggestion
    <!-- Show the CC Donate modal-->
```

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +  name: "cc-explore",
```suggestion
  name: "cc-donate",
```

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +    console.log("opted out?: ", userHasOptedOutFromDonationAppeal);
```suggestion
```

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +      Cookies.set("_ga", undefined);
I'm not sure we want to clear our Google Analytics cookie when users opt-out of the donation modal. GA seems like a separate concern.

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +  /*  background-color: #FEEDE9;*/
```suggestion
```

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +  /* height: 100px; */
```suggestion
```

2021-12-07 07:10 UTC, brylie commented on src/components/cc-donate.vue
> +  /*   width: auto; */
```suggestion
```

2021-12-07 07:13 UTC, brylie reviewed
Overall, we should discuss with @annatuma whether we want to include the donation modal in our CC global widgets library. I.e., do we intend to solicit donations using this widget in the future, or is the Google Tag Manager approach sustainable enough? We may decide not to use a donation appeal overlay, but we need to discuss it with other stakeholders.

2021-12-07 07:28 UTC, MuluhGodson commented
> Overall, we should discuss with @annatuma whether we want to include the donation modal in our CC global widgets library. I.e., do we intend to solicit donations using this widget in the future, or is the Google Tag Manager approach sustainable enough? We may decide not to use a donation appeal overlay, but we need to discuss it with other stakeholders.


That's a great idea. 
This PR is just a standby in case there is ever a need to include it into the CC Global components.

2021-12-07 07:38 UTC, brylie commented
I converted the PR to draft to indicate it is still under consideration since we are unsure about using modal dialogues for future fundraising.

Otherwise, the code looks good.

2021-12-07 17:40 UTC, annatuma commented
> Overall, we should discuss with @annatuma whether we want to include the donation modal in our CC global widgets library. I.e., do we intend to solicit donations using this widget in the future, or is the Google Tag Manager approach sustainable enough? We may decide not to use a donation appeal overlay, but we need to discuss it with other stakeholders.

Absolutely the right call Brylie - let's come back to this after discussing with stakeholders. Excellent to see the way we could implement this though is feasible.

2022-03-03 23:36 UTC, closed without merging